deploy:
  needs: build
  runs-on: ubuntu-latest
  env:
    # Crea antes este secreto en Settings → Secrets:
    #   Name: GCP_PROJECT_ID
    #   Value: tu ID de proyecto (por ej. chatbotprevencionretiro)
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    SHEET_ID:    ${{ secrets.SHEET_ID }}
  steps:
    - uses: actions/checkout@v3

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > cred.json
        gcloud auth activate-service-account --key-file=cred.json

    - name: Set GCP project
      run: |
        gcloud config set project $PROJECT_ID

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy chatbotWebhook \
          --project      $PROJECT_ID \
          --region       us-central1 \
          --runtime      nodejs18 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars SHEET_ID=$SHEET_ID
