name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Set GCP project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          gcloud functions deploy chatbotWebhook \
            --entry-point=chatbotWebhook \
            --region=us-central1 \
            --runtime=nodejs18 \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars SHEET_ID=$SHEET_ID

      - name: Register social channels
        if: success()
        env:
          FB_PAGE_TOKEN:    ${{ secrets.FB_PAGE_TOKEN }}
          TG_BOT_TOKEN:     ${{ secrets.TG_BOT_TOKEN }}
          FUNCTION_URL:     https://us-central1-${{ secrets.GCP_PROJECT_ID }}.cloudfunctions.net/chatbotWebhook
        run: |
          bash scripts/register-channels.sh

