name: CI/CD

on:
  push:
    branches: [ main ]        # o [ principal ] si tu rama principal se llama así

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > cred.json
          gcloud auth activate-service-account --key-file=cred.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          gcloud functions deploy chatbotWebhook \
            --region=us-central1 \
            --runtime=nodejs18 \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars SHEET_ID=$SHEET_ID,GOOGLE_CREDENTIALS="$(< cred.json)"

      - name: Register social channels
        env:
          FB_PAGE_TOKEN:     ${{ secrets.FB_PAGE_TOKEN }}
          TG_BOT_TOKEN:      ${{ secrets.TG_BOT_TOKEN }}
          CLOUD_FUNCTION_URL: https://us-central1-${{ secrets.GCP_PROJECT_ID }}.cloudfunctions.net/chatbotWebhook
        run: |
          bash scripts/register-channels.sh
